from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List

from qdp_io.artifacts import dump_json, sha256_file, stable_hash
from qdp_validation import validate_artifact_file as validate_file
from qdp_validation import validate_artifact_instance as validate_instance
from .control_plane import upsert_lab_request
from tools.workflow.qdp_runtime.qdp_governance import clip_candidate_with_caps, complete_governance_fallback
from tools.workflow.qdp_runtime.qdp_module_sdk import load_json
from tools.workflow.qdp_runtime.qdp_paths import (
    CALIBRATION_SNAPSHOT_SCHEMA,
    CANDIDATE_ARTIFACT_MANIFEST_SCHEMA,
    EXPERIMENT_REQUEST_SCHEMA,
    INSTRUMENT_PROFILE_SCHEMA,
    LAB_INGEST_REPORT,
    LAB_INGESTIONS_DIR,
    LAB_REQUEST_REPORT,
    LAB_REQUESTS_DIR,
    LINEAGE_RECORD_SCHEMA,
    RUN_RESULT_PACKET_SCHEMA,
)
from .run_ledger import record_run


def candidate_target_device_ids(candidate: Dict[str, Any]) -> List[str]:
    devices = candidate.get("candidate_target_devices", [])
    if isinstance(devices, list) and devices:
        return [str(item) for item in devices]
    cross = candidate.get("cross_device_validation", {})
    if isinstance(cross, dict):
        nested = cross.get("devices_tested", [])
        if isinstance(nested, list):
            return [str(item) for item in nested]
    return []


def build_candidate_artifact_manifest(candidate_path: Path, candidate: Dict[str, Any]) -> Dict[str, Any]:
    linked = []
    for item in candidate.get("linked_artifacts", []):
        path = Path(str(item))
        if path.exists() and path.is_file():
            linked.append({"path": str(path), "sha256": sha256_file(path)})
    return {
        "manifest_id": f"QDPMAN-{stable_hash({'candidate_id': candidate.get('candidate_id', ''), 'candidate_path': str(candidate_path)})[:16].upper()}",
        "candidate_id": candidate.get("candidate_id", ""),
        "candidate_path": str(candidate_path),
        "candidate_sha256": sha256_file(candidate_path),
        "linked_artifacts": linked,
    }


def default_instrument_profile(candidate: Dict[str, Any]) -> Dict[str, Any]:
    devices = candidate_target_device_ids(candidate)
    supported_measurements = candidate.get("experiment_schedule", {}).get("priority_experiments", [])
    if not isinstance(supported_measurements, list):
        supported_measurements = []
    return {
        "instrument_profile_id": f"QDPINST-{stable_hash({'candidate_id': candidate.get('candidate_id', ''), 'devices': devices})[:16].upper()}",
        "platform_class": str(candidate.get("accessible_platform_or_device_class", "") or "SURFACED_PLATFORM"),
        "device_ids": [str(item) for item in devices],
        "supported_measurements": [str(item) for item in supported_measurements],
        "instrument_facing_requirement_satisfied": True,
        "notes": ["Generated from candidate surfaced experiment schedule."],
    }


def pack_lab_request(
    *,
    candidate_path: Path,
    candidate: Dict[str, Any],
    lane: str,
    instrument_profile: Dict[str, Any],
    output_dir: Path,
) -> Dict[str, Any]:
    manifest = build_candidate_artifact_manifest(candidate_path, candidate)
    devices = candidate_target_device_ids(candidate)
    notes = ["Generated by qdp.py lab pack from surfaced candidate artifacts."]
    if isinstance(candidate.get("simulation_conditions", {}), dict) and candidate.get("simulation_conditions"):
        notes.append(
            "Branch-specific sweep axes remain on the candidate via simulation_conditions and tested_parameter_ranges; use the candidate manifest path to recover them."
        )
    elif isinstance(candidate.get("tested_parameter_ranges", {}), dict) and candidate.get("tested_parameter_ranges"):
        notes.append(
            "Branch-specific sweep axes remain on the candidate via tested_parameter_ranges; use the candidate manifest path to recover them."
        )
    request_hash = stable_hash(
        {
            "candidate_id": candidate.get("candidate_id", ""),
            "lane": lane,
            "candidate_sha256": manifest["candidate_sha256"],
            "instrument_profile_id": instrument_profile["instrument_profile_id"],
        }
    )
    request_id = f"QDPLAB-{request_hash[:16].upper()}"
    candidate_dir = output_dir / str(candidate.get("candidate_id", "unnamed"))
    candidate_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = candidate_dir / f"{request_id}_candidate_manifest.json"
    profile_path = candidate_dir / f"{request_id}_instrument_profile.json"
    request_path = candidate_dir / f"{request_id}_request_pack.json"

    request_pack = {
        "request_id": request_id,
        "candidate_id": candidate.get("candidate_id", ""),
        "branch_or_model_tag": candidate.get("branch_or_model_tag", ""),
        "lane": lane,
        "scheduler_state": "DRAFTED",
        "exact_falsifier": candidate.get("exact_falsifier", ""),
        "priority_experiments": candidate.get("experiment_schedule", {}).get("priority_experiments", []),
        "requested_output_artifacts": candidate.get("requested_output_artifacts", []),
        "candidate_target_devices": devices,
        "instrument_profile_ref": str(profile_path),
        "candidate_artifact_manifest_ref": str(manifest_path),
        "notes": notes,
    }

    dump_json(manifest_path, manifest)
    dump_json(profile_path, instrument_profile)
    dump_json(request_path, request_pack)

    validations = [
        validate_instance(manifest, CANDIDATE_ARTIFACT_MANIFEST_SCHEMA, artifact_kind="candidate_manifest"),
        validate_instance(instrument_profile, INSTRUMENT_PROFILE_SCHEMA, artifact_kind="instrument_profile"),
        validate_instance(request_pack, EXPERIMENT_REQUEST_SCHEMA, artifact_kind="experiment_request"),
    ]
    report = {
        "artifact_id": "QDP_V10_6_LAB_REQUEST_REPORT",
        "request_id": request_id,
        "request_pack_path": str(request_path),
        "candidate_artifact_manifest_path": str(manifest_path),
        "instrument_profile_path": str(profile_path),
        "validations": validations,
    }
    dump_json(LAB_REQUEST_REPORT, report)
    upsert_lab_request(
        {
            "request_id": request_id,
            "candidate_id": candidate.get("candidate_id", ""),
            "scheduler_state": "DRAFTED",
            "request_pack_path": str(request_path),
        }
    )
    record_run(
        operation="lab_pack",
        lane=lane,
        status="READY" if all(item["valid"] for item in validations) else "FAILED",
        summary={"request_id": request_id, "candidate_id": candidate.get("candidate_id", "")},
        artifacts=[request_path, manifest_path, profile_path, LAB_REQUEST_REPORT],
    )
    return {"request_pack": request_pack, "report": report, "request_pack_path": request_path}


def ingest_lab_result(
    *,
    candidate_path: Path,
    request_pack_path: Path,
    result_packet_path: Path,
    calibration_snapshot_path: Path,
    lineage_record_path: Path,
    updated_candidate_path: Path,
) -> Dict[str, Any]:
    from modules.m13_cross_device_gate.runner import run_cross_device_gate
    from modules.m14_promotion_caps.runner import run_promotion_caps
    from modules.m15_governance_guardrails.runner import run_governance_guardrails
    from tools.workflow.qdp_runtime.qdp_validation import validate_candidate_file
    from tools.workflow.qdp_runtime.qdp_paths import CANDIDATE_VALIDATOR, SCHEMA

    candidate = load_json(candidate_path)
    request_pack = load_json(request_pack_path)
    result_packet = load_json(result_packet_path)
    calibration_snapshot = load_json(calibration_snapshot_path)
    lineage_record = load_json(lineage_record_path)

    validations = [
        validate_file(request_pack_path, EXPERIMENT_REQUEST_SCHEMA, artifact_kind="experiment_request"),
        validate_file(result_packet_path, RUN_RESULT_PACKET_SCHEMA, artifact_kind="run_result_packet"),
        validate_file(calibration_snapshot_path, CALIBRATION_SNAPSHOT_SCHEMA, artifact_kind="calibration_snapshot"),
        validate_file(lineage_record_path, LINEAGE_RECORD_SCHEMA, artifact_kind="lineage_record"),
    ]

    candidate["candidate_target_devices"] = result_packet.get("devices_tested", [])
    candidate["multi_device_data_available"] = len(result_packet.get("devices_tested", [])) > 1
    candidate["fabrication_matched_for_geometry_claim"] = bool(result_packet.get("fabrication_matched", False))
    candidate.setdefault("cross_device_validation", {})
    candidate["cross_device_validation"]["status"] = result_packet.get("cross_device_status", "")
    candidate["cross_device_validation"]["devices_tested"] = result_packet.get("devices_tested", [])
    candidate["cross_device_validation"]["fabrication_matched"] = bool(result_packet.get("fabrication_matched", False))
    candidate["cross_device_validation"]["notes"] = "; ".join(result_packet.get("notes", []))
    candidate["calibration_validity_score"] = calibration_snapshot.get("validity_score")
    candidate.setdefault("calibration_status", {})
    candidate["calibration_status"]["status"] = calibration_snapshot.get("status", "")
    candidate["calibration_status"]["validity_score"] = calibration_snapshot.get("validity_score")
    candidate["calibration_status"]["threshold"] = calibration_snapshot.get("threshold")
    candidate["calibration_status"]["below_threshold"] = (
        isinstance(calibration_snapshot.get("validity_score"), (int, float))
        and calibration_snapshot.get("validity_score") < calibration_snapshot.get("threshold", 70)
    )
    candidate["calibration_status"]["notes"] = "; ".join(calibration_snapshot.get("notes", []))
    candidate.setdefault("dataset_governance", {})
    candidate["dataset_governance"]["device_lineage_recorded"] = bool(lineage_record.get("device_lineage_recorded", False))
    candidate["dataset_governance"]["calibration_context_recorded"] = bool(lineage_record.get("calibration_context_recorded", False))
    candidate["dataset_governance"]["protocol_metadata_recorded"] = bool(lineage_record.get("protocol_metadata_recorded", False))
    candidate["dataset_governance"]["notes"] = "; ".join(lineage_record.get("notes", []))
    candidate.setdefault("linked_artifacts", [])
    for artifact in [str(request_pack_path), str(result_packet_path), str(calibration_snapshot_path), str(lineage_record_path)]:
        if artifact not in candidate["linked_artifacts"]:
            candidate["linked_artifacts"].append(artifact)

    candidate, m13_report = run_cross_device_gate(candidate)
    candidate, m15_report = run_governance_guardrails(candidate)

    ladder = candidate.get("validation_ladder", {})
    if (
        candidate.get("cross_device_status") == "CONFIRMED"
        and all(bool(ladder.get(key, False)) for key in [
            "L0_baseline_pipeline_reproduced",
            "L1_reduction_limit_verified",
            "L2_convergence_plan_defined",
            "L3_numerical_stability_passed",
            "L4_instrument_facing_comparison_path_defined",
        ])
        and candidate.get("promotion_cap_governance", "") in {"", "PROCEED"}
    ):
        candidate["scientific_decision"] = "CROSS_DEVICE_CONFIRMED_IDENTIFIABLE"
        candidate["governance_outcome"] = "PROCEED"

    candidate, m14_report = run_promotion_caps(candidate)
    clip_candidate_with_caps(candidate)
    complete_governance_fallback(candidate)

    updated_candidate_path.parent.mkdir(parents=True, exist_ok=True)
    updated_candidate_path.write_text(json.dumps(candidate, indent=2), encoding="utf-8")
    candidate_validation = validate_candidate_file(updated_candidate_path, CANDIDATE_VALIDATOR, SCHEMA, mode="final")

    report = {
        "artifact_id": "QDP_V10_6_LAB_INGEST_REPORT",
        "request_id": request_pack.get("request_id", ""),
        "updated_candidate_path": str(updated_candidate_path),
        "validations": validations,
        "candidate_validation": candidate_validation,
        "module_reports": {
            "M13": m13_report,
            "M15": m15_report,
            "M14": m14_report,
        },
        "result_summary": {
            "cross_device_status": candidate.get("cross_device_status", ""),
            "governance_outcome": candidate.get("governance_outcome", ""),
            "scientific_decision": candidate.get("scientific_decision", ""),
        },
    }
    dump_json(LAB_INGEST_REPORT, report)
    upsert_lab_request(
        {
            "request_id": request_pack.get("request_id", ""),
            "candidate_id": candidate.get("candidate_id", ""),
            "scheduler_state": "INGESTED",
            "request_pack_path": str(request_pack_path),
            "result_packet_path": str(result_packet_path),
            "calibration_snapshot_path": str(calibration_snapshot_path),
            "lineage_record_path": str(lineage_record_path),
        }
    )
    record_run(
        operation="lab_ingest",
        lane=request_pack.get("lane", "recovery"),
        status="READY" if candidate_validation.get("valid", False) else "FAILED",
        summary={
            "request_id": request_pack.get("request_id", ""),
            "candidate_id": candidate.get("candidate_id", ""),
            "governance_outcome": candidate.get("governance_outcome", ""),
        },
        artifacts=[request_pack_path, result_packet_path, calibration_snapshot_path, lineage_record_path, updated_candidate_path, LAB_INGEST_REPORT],
    )
    return {"candidate": candidate, "report": report}

